import type { BuiltinGroupType } from "../catalog/entityGroups";

export type EntityTemplateGroupType = Exclude<BuiltinGroupType, "apps-infra">;

function withAppRoot(appName: string, bodyLines: string[]): string[] {
  return [`  ${appName}:`, ...bodyLines];
}

export function renderEntityTemplateLines(groupType: string, appName: string): string[] {
  switch (groupType as EntityTemplateGroupType) {
    case "apps-stateless":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # HTTP stateless app template: service + probes + autoscaling hooks",
        "    _include: [\"apps-stateless-defaultApp\"]",
        "    containers:",
        `      ${appName}:`,
        "        image:",
        "          name: ghcr.io/acme/platform-api",
        "          staticTag: \"1.0.0\"",
        "        envVars:",
        "          APP_ENV: \"{{ $.Values.global.env }}\"",
        "          LOG_LEVEL:",
        "            _default: info",
        "            prod: warn",
        "          HTTP_PORT: \"8080\"",
        "        resources:",
        "          requests:",
        "            mcpu: 100",
        "            memoryMb: 256",
        "          limits:",
        "            mcpu: 500",
        "            memoryMb: 512",
        "        ports: |-",
        "          - name: http",
        "            containerPort: 8080",
        "        readinessProbe: |-",
        "          httpGet:",
        "            path: /ready",
        "            port: 8080",
        "          initialDelaySeconds: 5",
        "          periodSeconds: 10",
        "        livenessProbe: |-",
        "          httpGet:",
        "            path: /health",
        "            port: 8080",
        "          initialDelaySeconds: 15",
        "          periodSeconds: 15",
        "    initContainers:",
        "      wait-db:",
        "        image:",
        "          name: busybox",
        "          staticTag: \"1.36\"",
        "        command: |-",
        "          - sh",
        "        args: |-",
        "          - -c",
        "          - until nc -z postgres 5432; do echo waiting for db; sleep 2; done",
        "    service:",
        "      enabled: true",
        "      type: ClusterIP",
        "      ports: |-",
        "        - name: http",
        "          port: 80",
        "          targetPort: 8080",
        "    serviceAccount:",
        "      name: app-runtime",
        "    podDisruptionBudget:",
        "      enabled: true",
        "      minAvailable: 1",
        "    horizontalPodAutoscaler:",
        "      enabled: false",
        "      minReplicas: 2",
        "      maxReplicas: 8",
        "    verticalPodAutoscaler:",
        "      enabled: false",
      ]);

    case "apps-stateful":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Stateful workload template: stable identity + persistent data",
        "    _include: [\"apps-stateful-defaultApp\"]",
        "    containers:",
        `      ${appName}:`,
        "        image:",
        "          name: ghcr.io/acme/platform-stateful",
        "          staticTag: \"1.0.0\"",
        "        envVars:",
        "          APP_ENV: \"{{ $.Values.global.env }}\"",
        "          DATA_DIR: /var/lib/app",
        "        resources:",
        "          requests:",
        "            mcpu: 300",
        "            memoryMb: 512",
        "          limits:",
        "            mcpu: 1500",
        "            memoryMb: 2048",
        "        ports: |-",
        "          - name: http",
        "            containerPort: 8080",
        "        volumeMounts: |-",
        "          - name: data",
        "            mountPath: /var/lib/app",
        "    initContainers:",
        "      init-permissions:",
        "        image:",
        "          name: busybox",
        "          staticTag: \"1.36\"",
        "        command: |-",
        "          - sh",
        "        args: |-",
        "          - -c",
        "          - chown -R 1000:1000 /var/lib/app",
        "        volumeMounts: |-",
        "          - name: data",
        "            mountPath: /var/lib/app",
        "    volumes: |-",
        "      - name: data",
        "        persistentVolumeClaim:",
        "          claimName: app-data",
        "    service:",
        "      enabled: true",
        "      headless: true",
        "      ports: |-",
        "        - name: http",
        "          port: 80",
        "          targetPort: 8080",
        "    serviceAccount:",
        "      name: app-stateful",
        "    verticalPodAutoscaler:",
        "      enabled: false",
      ]);

    case "apps-jobs":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # One-shot batch/migration template",
        "    _include: [\"apps-jobs-defaultJob\"]",
        "    restartPolicy: OnFailure",
        "    backoffLimit: 3",
        "    activeDeadlineSeconds: 1800",
        "    serviceAccount:",
        "      name: jobs-runner",
        "    initContainers:",
        "      wait-db:",
        "        image:",
        "          name: busybox",
        "          staticTag: \"1.36\"",
        "        command: |-",
        "          - sh",
        "        args: |-",
        "          - -c",
        "          - until nc -z postgres 5432; do echo waiting for db; sleep 2; done",
        "    containers:",
        `      ${appName}:`,
        "        image:",
        "          name: ghcr.io/acme/db-migrate",
        "          staticTag: \"1.0.0\"",
        "        command: |-",
        "          - sh",
        "        args: |-",
        "          - -c",
        "          - ./scripts/migrate.sh",
        "        envVars:",
        "          APP_ENV: \"{{ $.Values.global.env }}\"",
        "        resources:",
        "          requests:",
        "            mcpu: 100",
        "            memoryMb: 256",
        "          limits:",
        "            mcpu: 500",
        "            memoryMb: 512",
      ]);

    case "apps-cronjobs":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Periodic maintenance/report template",
        "    _include: [\"apps-cronjobs-defaultCronJob\"]",
        "    schedule: \"*/15 * * * *\"",
        "    concurrencyPolicy: Forbid",
        "    startingDeadlineSeconds: 180",
        "    successfulJobsHistoryLimit: 3",
        "    failedJobsHistoryLimit: 1",
        "    serviceAccount:",
        "      name: cron-runner",
        "    containers:",
        `      ${appName}:`,
        "        image:",
        "          name: ghcr.io/acme/cron-task",
        "          staticTag: \"1.0.0\"",
        "        command: |-",
        "          - sh",
        "        args: |-",
        "          - -c",
        "          - ./scripts/run-cron.sh",
        "        envVars:",
        "          APP_ENV: \"{{ $.Values.global.env }}\"",
        "        resources:",
        "          requests:",
        "            mcpu: 50",
        "            memoryMb: 128",
        "          limits:",
        "            mcpu: 300",
        "            memoryMb: 512",
      ]);

    case "apps-services":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Standalone Service template for exposing existing pods",
        "    type: ClusterIP",
        "    selector: |-",
        "      app.kubernetes.io/name: app-1",
        "    ports: |-",
        "      - name: http",
        "        port: 80",
        "        targetPort: 8080",
      ]);

    case "apps-ingresses":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Public entrypoint template",
        "    _include: [\"apps-ingresses-defaultIngress\"]",
        "    ingressClassName: nginx",
        "    host: app.example.local",
        "    hosts: |-",
        "      - app.example.local",
        "    paths: |-",
        "      - path: /",
        "        pathType: Prefix",
        "    tls:",
        "      enabled: true",
        "      secret_name: app-example-local-tls",
        "    dexAuth:",
        "      enabled: false",
      ]);

    case "apps-network-policies":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Network access policy template (start from deny + allow-list)",
        "    _include: [\"apps-network-policies-defaultNetworkPolicy\"]",
        "    type: kubernetes",
        "    podSelector: |-",
        "      matchLabels:",
        "        app.kubernetes.io/name: app-1",
        "    policyTypes: |-",
        "      - Ingress",
        "      - Egress",
        "    ingress: |-",
        "      - from:",
        "          - namespaceSelector:",
        "              matchLabels:",
        "                kubernetes.io/metadata.name: ingress-nginx",
        "          - podSelector:",
        "              matchLabels:",
        "                app.kubernetes.io/name: api-gateway",
        "    egress: |-",
        "      - to:",
        "          - namespaceSelector:",
        "              matchLabels:",
        "                kubernetes.io/metadata.name: kube-system",
        "        ports:",
        "          - protocol: UDP",
        "            port: 53",
      ]);

    case "apps-configmaps":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Non-sensitive runtime config",
        "    _include: [\"apps-configmaps-defaultConfigmap\"]",
        "    data:",
        "      APP_MODE: \"service\"",
        "      LOG_LEVEL: \"info\"",
        "      FEATURE_FLAG_X: \"false\"",
        "    binaryData:",
        "      logo.png: \"<base64-content>\"",
        "    envVars:",
        "      APP_MODE: service",
        "      LOG_LEVEL:",
        "        _default: info",
        "        prod: warn",
      ]);

    case "apps-secrets":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Sensitive data (prefer external secret manager in production)",
        "    _include: [\"apps-secrets-defaultSecret\"]",
        "    type: Opaque",
        "    # For GitOps onboarding prefer stringData; Kubernetes converts it to data",
        "    stringData:",
        "      DB_USER: app",
        "      DB_PASSWORD: \"change-me\"",
        "    data:",
        "      DB_USER: app",
        "      # data values are typically base64 in raw Kubernetes Secret manifests",
        "      DB_PASSWORD: Y2hhbmdlLW1l",
        "    binaryData:",
        "      ca.crt: \"<base64-cert>\"",
        "    immutable: false",
        "    envVars:",
        "      DB_USER: app",
      ]);

    case "apps-pvcs":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Persistent disk claim template",
        "    storageClassName: gp3",
        "    accessModes: |-",
        "      - ReadWriteOnce",
        "    resources: |-",
        "      requests:",
        "        storage: 10Gi",
      ]);

    case "apps-limit-range":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Namespace resource policy limits",
        "    limits: |-",
        "      - type: Container",
        "        default:",
        "          cpu: 500m",
        "          memory: 512Mi",
        "        defaultRequest:",
        "          cpu: 100m",
        "          memory: 128Mi",
      ]);

    case "apps-certificates":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # cert-manager certificate template",
        "    # First thing to change: clusterIssuer and DNS names",
        "    clusterIssuer: letsencrypt-prod",
        "    host: app.example.local",
        "    hosts: |-",
        "      - app.example.local",
      ]);

    case "apps-dex-clients":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # OAuth client entry for Dex",
        "    # First thing to change: callback URL(s) for your app",
        "    redirectURIs: |-",
        "      - https://app.example.local/callback",
        "      - https://app.example.local/oauth2/callback",
      ]);

    case "apps-dex-authenticators":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Ingress auth helper based on DexAuthenticator",
        "    # First thing to change: public domain + TLS secret",
        "    applicationDomain: auth.example.local",
        "    applicationIngressClassName: nginx",
        "    applicationIngressCertificateSecretName: auth-example-local-tls",
        "    keepUsersLoggedInFor: 168h",
        "    signOutURL: https://auth.example.local/sign_out",
        "    allowedGroups: |-",
        "      - platform-admins",
        "      - devops",
        "    sendAuthorizationHeader: true",
        "    whitelistSourceRanges: |-",
        "      - 10.0.0.0/8",
        "      - 192.168.0.0/16",
        "    nodeSelector: |-",
        "      node-role.kubernetes.io/system: \"true\"",
        "    tolerations: |-",
        "      - key: node-role.kubernetes.io/system",
        "        operator: Exists",
      ]);

    case "apps-custom-prometheus-rules":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Alerting rules bundle",
        "    # First thing to change: alert expression + threshold",
        "    groups:",
        "      app.rules:",
        "        alerts:",
        "          highErrorRate:",
        "            isTemplate: false",
        "            content: |-",
        "              expr: sum(rate(http_requests_total{status=~\"5..\"}[5m])) > 5",
        "              for: 5m",
        "              labels:",
        "                severity: warning",
        "              annotations:",
        "                summary: High 5xx error rate",
      ]);

    case "apps-grafana-dashboards":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Dashboard JSON should be stored in dashboards/<name>.json",
        "    # First thing to change: target folder for dashboard placement",
        "    folder: Platform",
      ]);

    case "apps-kafka-strimzi":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Strimzi stack template (advanced infra workload)",
        "    # First thing to change: version/replicas/storage according to cluster capacity",
        "    priorityClassName: production-high",
        "    prometheusSampleLimit: 10000",
        "    version: 3.7.0",
        "    replicas: 3",
        "    resources:",
        "      requests:",
        "        mcpu: 500",
        "        memoryMb: 1024",
        "      limits:",
        "        mcpu: 2000",
        "        memoryMb: 4096",
        "    storage:",
        "      size: 20Gi",
        "      class: gp3",
        "    jvmOptions: |-",
        "      -Xms2g -Xmx2g",
        "    tolerations: |-",
        "      - key: dedicated",
        "        operator: Equal",
        "        value: kafka",
        "        effect: NoSchedule",
        "    zookeeper:",
        "      replicas: 3",
        "      resources:",
        "        requests:",
        "          mcpu: 200",
        "          memoryMb: 512",
        "        limits:",
        "          mcpu: 1000",
        "          memoryMb: 2048",
        "      storage:",
        "        size: 20Gi",
        "        class: gp3",
        "      metricsConfig: |-",
        "        type: jmxPrometheusExporter",
        "        valueFrom:",
        "          configMapKeyRef:",
        "            name: zookeeper-metrics",
        "            key: zookeeper-metrics-config.yml",
        "      jvmOptions: |-",
        "        -Xms512m -Xmx512m",
        "    entityOperator:",
        "      topicOperator:",
        "        resources:",
        "          requests:",
        "            mcpu: 100",
        "            memoryMb: 256",
        "      userOperator:",
        "        resources:",
        "          requests:",
        "            mcpu: 100",
        "            memoryMb: 256",
        "    exporter:",
        "      resources:",
        "        requests:",
        "          mcpu: 100",
        "          memoryMb: 256",
        "    deckhouseMetrics:",
        "      kafka-lag:",
        "        enabled: true",
        "        expr: sum(kafka_consumergroup_lag)",
        "        threshold: 10000",
        "    topics:",
        "      app-events:",
        "        partitions: 3",
        "        replicas: 3",
        "        retention: 604800000",
        "        segment_bytes: 1073741824",
        "        min_insync_replicas: 2",
      ]);

    case "apps-service-accounts":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # RBAC template with namespaced and cluster-scoped permissions",
        "    # First thing to change: rules/verbs to least-privilege set",
        "    name: app-runtime",
        "    namespace: apps",
        "    automountServiceAccountToken: false",
        "    roles:",
        "      pod-reader:",
        "        rules: |-",
        "          - apiGroups: [\"\"]",
        "            resources: [\"pods\"]",
        "            verbs: [\"get\", \"list\", \"watch\"]",
        "    clusterRoles:",
        "      metrics-reader:",
        "        rules: |-",
        "          - apiGroups: [\"metrics.k8s.io\"]",
        "            resources: [\"pods\"]",
        "            verbs: [\"get\", \"list\"]",
        "        binding:",
        "          subjects: |-",
        "            - kind: Group",
        "              name: observability-readers",
        "              apiGroup: rbac.authorization.k8s.io",
      ]);

    case "apps-k8s-manifests":
      return withAppRoot(appName, [
        "    enabled: true",
        "    # Generic Kubernetes manifest fallback template",
        "    apiVersion: v1",
        "    kind: ConfigMap",
        "    fieldsYAML:",
        "      metadata: |-",
        "        labels:",
        "          app.kubernetes.io/name: app-1",
        "      data: |-",
        "        FEATURE_X: \"true\"",
        "    extraFields:",
        "      immutable: false",
      ]);
  }

  return withAppRoot(appName, [
    "    enabled: true",
  ]);
}

export function renderAppsInfraTemplateLines(
  options: { includeNodeUsers?: boolean; includeNodeGroups?: boolean } = {},
): string[] {
  const includeNodeUsers = options.includeNodeUsers ?? true;
  const includeNodeGroups = options.includeNodeGroups ?? true;
  const lines: string[] = [];

  if (includeNodeUsers) {
    lines.push(
      "  node-users:",
      "    deploy:",
      "      enabled: true",
      "      uid: 10001",
      "      isSudoer: false",
      "      nodeGroups: |-",
      "        - workers",
      "      sshPublicKeys: |-",
      "        - ssh-ed25519 AAAA... replace-with-real-key",
    );
  }

  if (includeNodeGroups) {
    lines.push(
      "  node-groups:",
      "    workers:",
      "      enabled: true",
      "      labels: |-",
      "        role: worker",
    );
  }

  return lines;
}
